#index:
#    path: /
#    controller: App\Controller\DefaultController::index
captcha_routing:
   resource: "@CaptchaBundle/Resources/config/routing.yml"

pdf:
   path: /pdf
   controller: App\Controller\FormationController::indexpdf
